name: Cache Speedup Test

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Cache dependencies
      - name: prime-cache-a108a37
        id: cache-step
        uses: actions/cache@v4
        with:
          path: ~/.cache/example
          key: cache-a108a37

      - name: Check cache result
        run: |
          echo "Cache hit: ${{ steps.cache-step.outputs.cache-hit }}"
